FROM mcr.microsoft.com/devcontainers/java:1-21-bullseye

# ARG USERNAME=shinyay
# ARG USER_UID=1001
# ARG USER_GID=${USER_UID}

# RUN apt-get update \
#     && groupadd --gid ${USER_UID} ${USERNAME} \
#     && useradd -s /bin/bash --uid $USER_UID --gid ${USER_GID} -m ${USERNAME}
#     # && apt-get install -y sudo \
#     # && echo ${USERNAME} ALL=\(\root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
#     # && chmod 0440 /etc/sodoers.d/${USERNAME}

# USER shinyay
WORKDIR /workspace